"""add_prix_fixe_to_rental_types

Revision ID: 7d5867577a4e
Revises: e4f569f07c4f
Create Date: 2026-06-20 20:10:24.037764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5867577a4e'
down_revision: Union[str, Sequence[str], None] = 'e4f569f07c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prix_fixe', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_types', schema=None) as batch_op:
        batch_op.drop_column('prix_fixe')

    # ### end Alembic commands ###
