"""add depart_coords arrivee_coords to locations

Revision ID: 9038dcebba51
Revises: 799b33d1e864
Create Date: 2026-08-26 00:52:49.121528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9038dcebba51'
down_revision: Union[str, Sequence[str], None] = '799b33d1e864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depart_coords', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('arrivee_coords', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('arrivee_coords')
        batch_op.drop_column('depart_coords')

    # ### end Alembic commands ###
