"""add_voiture_typelocation_location_tables

Revision ID: 9741b089a73a
Revises: de7cd4fe5cb1
Create Date: 2026-06-22 00:46:27.895539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9741b089a73a'
down_revision: Union[str, Sequence[str], None] = 'de7cd4fe5cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voitures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marque', sa.String(length=50), nullable=False),
    sa.Column('modele', sa.String(length=50), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('immatriculation', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('consommation_carburant', sa.Float(), nullable=False),
    sa.Column('places', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('immatriculation')
    )
    op.create_table('types_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voiture_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prix', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['voiture_id'], ['voitures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voiture_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voiture_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['voiture_id'], ['voitures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voiture_id', sa.Integer(), nullable=False),
    sa.Column('type_location_id', sa.Integer(), nullable=True),
    sa.Column('client_nom', sa.String(length=100), nullable=False),
    sa.Column('client_telephone', sa.String(length=20), nullable=False),
    sa.Column('client_email', sa.String(length=100), nullable=True),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('prix_total', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('itineraire_distance_km', sa.Float(), nullable=True),
    sa.Column('itineraire_depart', sa.String(length=255), nullable=True),
    sa.Column('itineraire_arrivee', sa.String(length=255), nullable=True),
    sa.Column('itineraire_etapes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['type_location_id'], ['types_location.id'], ),
    sa.ForeignKeyConstraint(['voiture_id'], ['voitures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    op.drop_table('voiture_images')
    op.drop_table('types_location')
    op.drop_table('voitures')
    # ### end Alembic commands ###
