"""drop_old_tables_car_rental_type_rental

Revision ID: 9e67e624d9f9
Revises: 9741b089a73a
Create Date: 2026-06-22 00:58:17.280861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e67e624d9f9'
down_revision: Union[str, Sequence[str], None] = '9741b089a73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_images')
    op.drop_table('cars')
    op.drop_table('rental_types')
    op.drop_table('rentals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('customer_phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('customer_email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('car_id', sa.INTEGER(), nullable=False),
    sa.Column('rental_type_id', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('itinerary_distance_km', sa.FLOAT(), nullable=True),
    sa.Column('itinerary_start_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('itinerary_end_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('itinerary_waypoints', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['rental_type_id'], ['rental_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('duration_days', sa.INTEGER(), nullable=False),
    sa.Column('price_multiplier', sa.FLOAT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('discount_percent', sa.FLOAT(), nullable=False),
    sa.Column('prix_fixe', sa.FLOAT(), nullable=True),
    sa.Column('fuel_consumption', sa.FLOAT(), nullable=True),
    sa.Column('fuel_price', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=50), nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('plate_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('daily_price', sa.FLOAT(), nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('seats', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('fuel_consumption', sa.FLOAT(), server_default=sa.text("'8.0'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('car_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('car_id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
