"""simplify_voiture_nom_only_drop_typelocation_description

Revision ID: a75a46871ff0
Revises: 9e67e624d9f9
Create Date: 2026-06-22 01:06:07.788047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75a46871ff0'
down_revision: Union[str, Sequence[str], None] = '9e67e624d9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('types_location', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('voitures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.String(length=100), nullable=False))
        batch_op.drop_column('description')
        batch_op.drop_column('modele')
        batch_op.drop_column('immatriculation')
        batch_op.drop_column('annee')
        batch_op.drop_column('marque')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voitures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marque', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('annee', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('immatriculation', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('modele', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('nom')

    with op.batch_alter_table('types_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
