"""add analytics_events table

Revision ID: ce7013874243
Revises: 7ef94582e88c
Create Date: 2026-08-23 01:25:50.240779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7013874243'
down_revision: Union[str, Sequence[str], None] = '7ef94582e88c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('depart_lat', sa.Float(), nullable=True),
    sa.Column('depart_lon', sa.Float(), nullable=True),
    sa.Column('arrivee_lat', sa.Float(), nullable=True),
    sa.Column('arrivee_lon', sa.Float(), nullable=True),
    sa.Column('depart_nom', sa.String(length=120), nullable=True),
    sa.Column('arrivee_nom', sa.String(length=120), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('voiture_id', sa.Integer(), nullable=True),
    sa.Column('type_location_id', sa.Integer(), nullable=True),
    sa.Column('prix', sa.Float(), nullable=True),
    sa.Column('referer_host', sa.String(length=120), nullable=True),
    sa.Column('hour_local', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['type_location_id'], ['types_location.id'], ),
    sa.ForeignKeyConstraint(['voiture_id'], ['voitures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_created_at'))

    op.drop_table('analytics_events')
    # ### end Alembic commands ###
