"""add_fuel_consumption_to_rental_types

Revision ID: de7cd4fe5cb1
Revises: 7d5867577a4e
Create Date: 2026-06-20 20:53:06.337284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7cd4fe5cb1'
down_revision: Union[str, Sequence[str], None] = '7d5867577a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_consumption', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_types', schema=None) as batch_op:
        batch_op.drop_column('fuel_consumption')

    # ### end Alembic commands ###
